fos_rest:
    body_listener: true
    param_fetcher_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json, prefer_extension: false }
    view:
        view_response_listener: true
        formats:
           json: true
           xml : true
        templating_formats:
           html: true
